### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by dtannyc1** [dtannyc1/Davescord#7]
- [x] Need Demo Login Button on Create an Account modal
- [x] Investigate 401 error for csrf.js? (on new server creation)
  - 422 error whenever you switch servers? - happening b/c of existing subscriptions
- [x] Remove weird scrollbar on user name that appears in Chrome
- [x] Add second demo user for easier websocket testing
- [x] Add user menu - change username, image, email, color, password & log out
- [x] What's causing reloads when switching servers?
  - ChannelsPage component runs a useEffect fetch server and then a redirect, causing all children to rerender
- [ ] General reorganization of components to make it easier to navigate
- [x] Move navbar on splash page back up
